name: Changelogs

on:
    workflow_dispatch:
    release:
        types:
            - created
            - edited
            - published
            - released

jobs:
    changelogs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x

            - name: Install dependencies
              run: yarn --dev

            - name: Update changes
              uses: actions/github-script@v4
              with:
                  script: |
                      const got = require("got").default;
                      const getChanges = require("./scripts/utils/get-changes");

                      const changes = await getChanges({
                            repo: {
                                author: "zyrouge",
                                repo: "yukino-app",
                            },
                            version: {
                                previous: previous.tag_name,
                                current: latest.tag_name,
                            },
                      });

                      const logs = `**Changelogs**\n\n${changes.split("\n").map(x => `- ${x}`).join("\n")}`;
                      let body = latest.body || "";

                      const changelogsRegex = /(\*\*Changelogs\*\*[\s\S]+)/;
                      if (changelogsRegex.test(body)) {
                          body = body.replace(changelogsRegex, logs);
                      } else {
                          body += `\n\n${logs}`;
                      }

                      await github.request("POST /repos/{owner}/{repo}/releases/{release_id}", {
                          ...context.repo,
                          release_id: latest.id,
                          body
                      });
