name: Preview (Electron - Windows)

on:
    workflow_dispatch:

jobs:
    preview:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "14.16.0"

            - name: Install dependencies
              run: yarn --dev

            - name: Build
              run: yarn electron:build -w
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Windows Setup - Preview
                  path: dist/electron/*.exe
