name: Publish (Capacitor - Android)

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    android:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x

            - uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: adopt

            - name: Install dependencies
              run: yarn --dev

            - name: Build APK
              run: yarn capacitor:android:release

            - name: Sign APK
              uses: r0adkll/sign-android-release@v1
              id: signed_app
              with:
                  releaseDirectory: ${{ github.workspace }}/environments/capacitor/android/app/build/outputs/apk/release
                  signingKeyBase64: ${{ secrets.ANDROID_SIGN_KEY }}
                  alias: ${{ secrets.ANDROID_SIGN_ALIAS }}
                  keyStorePassword: ${{ secrets.ANDROID_SIGN_STORE_PASSWORD }}
                  keyPassword: ${{ secrets.ANDROID_SIGN_KEY_PASSWORD }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Signed APK
                  path: ${{ steps.signed_app.outputs.signedReleaseFile }}

            - name: Get app version
              uses: actions/github-script@v4
              id: app_version
              with:
                  result-encoding: string
                  script: |
                      const packageJson = require("${{ github.workspace }}/package.json");
                      return packageJson.version;

            - name: Create tag and upload
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  artifact: ${{ steps.signed_app.outputs.signedReleaseFile }}
                  commit: v${{ steps.app_version.outputs.result }}
                  name: v${{ steps.app_version.outputs.result }}
                  draft: true
                  token: ${{ secrets.GITHUB_TOKEN }}
