name: Publish

on:
    create:
    workflow_dispatch:

jobs:
    release:
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "14.16.0"

            - name: Install dependencies
              run: yarn --dev

            - name: Publish
              run: yarn electron:publish
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
