name: Publish (Capacitor - Android)

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    android:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.16.0

            - name: Install dependencies
              run: yarn --dev

            - name: Set up our JDK environment
              uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: adopt

            - name: Build Environment
              run: yarn capacitor:android:build

            - name: Generate APK
              run: yarn capacitor:android:release

            - name: Sign APK
              uses: r0adkll/sign-android-release@v1
              id: sign_app
              with:
                  releaseDirectory: ${{ github.workspace }}/environments/capacitor/android/app/build/outputs/apk/release
                  signingKeyBase64: ${{ secrets.ANDROID_SIGN_KEY }}
                  alias: ${{ secrets.ANDROID_SIGN_ALIAS }}
                  keyStorePassword: ${{ secrets.ANDROID_SIGN_STORE_PASSWORD }}
                  keyPassword: ${{ secrets.ANDROID_SIGN_KEY_PASSWORD }}
