name: Publish (Capacitor - Android)

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    android:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x

            - uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: adopt

            - name: Install dependencies
              run: yarn --dev

            - name: Build APK
              run: yarn capacitor:android:release

            - name: Sign APK
              uses: r0adkll/sign-android-release@v1
              id: signed_app
              with:
                  releaseDirectory: ${{ github.workspace }}/environments/capacitor/android/app/build/outputs/apk/release
                  signingKeyBase64: ${{ secrets.ANDROID_SIGN_KEY }}
                  alias: ${{ secrets.ANDROID_SIGN_ALIAS }}
                  keyStorePassword: ${{ secrets.ANDROID_SIGN_STORE_PASSWORD }}
                  keyPassword: ${{ secrets.ANDROID_SIGN_KEY_PASSWORD }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Signed APK
                  path: ${{ steps.signed_app.outputs.signedReleaseFile }}

            - name: Get app version
              uses: actions/github-script@v4
              id: app_version
              with:
                  result-encoding: string
                  script: |
                      const packageJson = require("./package.json");
                      return packageJson.version;

            - name: Do necessary modifications
              uses: actions/github-script@v4
              id: app_path
              env:
                  SIGNED_APK_PATH: ${{ steps.signed_app.outputs.signedReleaseFile }}
              with:
                  result-encoding: string
                  script: |
                      const path = require("path");
                      const fs = require("fs");
                      const packageJson = require("./package.json");

                      const inFile = process.env.SIGNED_APK_PATH;
                      const outFile = path.join(path.dirname(inFile), `${packageJson.productName}-${packageJson.version}.apk`);
                      fs.renameSync(inFile, outFile);
                      return outFile;

            - name: Create and upload to release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  artifacts: ${{ steps.app_path.outputs.result }}
                  name: ${{ steps.app_version.outputs.result }}
                  tag: v${{ steps.app_version.outputs.result }}
                  draft: true
                  token: ${{ secrets.GITHUB_TOKEN }}
